# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:


#services:
#    service_name:
#        class: RecipeBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

services:
  recipebundle.unique_collection:
    class: RecipeBundle\Form\Validator\UniqueCollectionValidator
    arguments: ["@request_stack"]
    tags:
      - { name: validator.constraint_validator, alias: unique_collection }